# Generated by Django 4.0.4 on 2023-05-24 16:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('passcode', models.CharField(max_length=30)),
                ('notification_settings', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1)),
            ],
        ),
    ]
